"""emission factors and calculation traceability

Revision ID: b4340efa8bf6
Revises: c6935fb99fa5
Create Date: 2026-10-02 07:39:49.003773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4340efa8bf6'
down_revision: Union[str, Sequence[str], None] = 'c6935fb99fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('kg_co2e_per_unit', sa.Float(), nullable=False),
    sa.Column('uncertainty_pct', sa.Float(), nullable=True),
    sa.Column('geography', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', 'source_version', name='uq_emission_factor_source')
    )
    op.create_index(op.f('ix_emission_factors_id'), 'emission_factors', ['id'], unique=False)
    op.create_index(op.f('ix_emission_factors_name'), 'emission_factors', ['name'], unique=False)
    op.create_index(op.f('ix_emission_factors_source'), 'emission_factors', ['source'], unique=False)
    op.add_column('emission_records', sa.Column('calc_method', sa.String(length=30), server_default='direct_input', nullable=False))
    op.add_column('emission_records', sa.Column('activity_quantity', sa.Float(), nullable=True))
    op.add_column('emission_records', sa.Column('activity_unit', sa.String(length=50), nullable=True))
    op.add_column('emission_records', sa.Column('emission_factor_id', sa.Integer(), nullable=True))
    op.add_column('emission_records', sa.Column('factor_kg_co2e_per_unit', sa.Float(), nullable=True))
    op.add_column('emission_records', sa.Column('factor_unit', sa.String(length=50), nullable=True))
    op.add_column('emission_records', sa.Column('factor_source_version', sa.String(length=50), nullable=True))
    op.add_column('emission_records', sa.Column('factor_uncertainty_pct', sa.Float(), nullable=True))
    op.create_index(op.f('ix_emission_records_emission_factor_id'), 'emission_records', ['emission_factor_id'], unique=False)
    op.create_foreign_key(None, 'emission_records', 'emission_factors', ['emission_factor_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emission_records', type_='foreignkey')
    op.drop_index(op.f('ix_emission_records_emission_factor_id'), table_name='emission_records')
    op.drop_column('emission_records', 'factor_uncertainty_pct')
    op.drop_column('emission_records', 'factor_source_version')
    op.drop_column('emission_records', 'factor_unit')
    op.drop_column('emission_records', 'factor_kg_co2e_per_unit')
    op.drop_column('emission_records', 'emission_factor_id')
    op.drop_column('emission_records', 'activity_unit')
    op.drop_column('emission_records', 'activity_quantity')
    op.drop_column('emission_records', 'calc_method')
    op.drop_index(op.f('ix_emission_factors_source'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_name'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_id'), table_name='emission_factors')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
